[libraries]
# Platforms
platform-paper = { module = "io.papermc.paper:paper-api", version = "1.19.4-R0.1-SNAPSHOT" }

# Webhook clients
client-discord = { module = "club.minnced:discord-webhooks", version = "0.8.2" }

# Libraries
dazzleconfig = { module = "space.arim.dazzleconf:dazzleconf-ext-snakeyaml", version = "1.3.0-M1" }
mcdiscordreserializer = { module = "dev.vankka:mcdiscordreserializer", version = "4.3.0" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.7" }

[plugins]
indra = { id = "net.kyori.indra", version = "3.0.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }