[versions]
bstats = "3.0.2"

[libraries]
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

# Platforms
platform-paper = { module = "io.papermc.paper:paper-api", version = "1.20.4-R0.1-SNAPSHOT" }

# Webhook clients
client-discord = { module = "io.github.4drian3d:jdwebhooks", version = "1.0.1" }

# Libraries
adventure = { module = "net.kyori:adventure-api", version = "4.15.0" }
dazzleconf = { module = "space.arim.dazzleconf:dazzleconf-ext-snakeyaml", version = "1.3.0-M1" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.7" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.0"}

[plugins]
indra = { id = "net.kyori.indra", version = "3.0.1" }
minotaur = { id = "com.modrinth.minotaur", version = "2.7.5"}
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version = "0.5.3" }